FROM openjdk:23-jdk-slim

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    findutils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

EXPOSE 8080

CMD ["./gradlew", "bootRun"]
